src/Entity/Section.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ApiResource(
 *     collectionOperations={"get"},
 *     itemOperations={"get"}
 * )
 * @ORM\Entity(repositoryClass="App\Repository\SectionRepository")
 */
class Section
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $content;

    /**
     * @ORM\Column(type="integer")
     */
    private $position;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $is_project;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $is_skill;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Item", mappedBy="section", orphanRemoval=true)
     */
    private $items;

    public function __toString()
    {
        return $this->title;
    }

    public function __construct()
    {
        $this->items = new ArrayCollection();
    }

    public function getId()
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getPosition(): ?int
    {
        return $this->position;
    }

    public function setPosition(int $position): self
    {
        $this->position = $position;

        return $this;
    }

    public function getIsProject(): ?bool
    {
        return $this->is_project;
    }

    public function setIsProject(?bool $is_project): self
    {
        $this->is_project = $is_project;

        return $this;
    }

    public function getIsSkill(): ?bool
    {
        return $this->is_skill;
    }

    public function setIsSkill(?bool $is_skill): self
    {
        $this->is_skill = $is_skill;

        return $this;
    }

    /**
     * @return Collection|Item[]
     */
    public function getItems(): Collection
    {
        return $this->items;
    }

    public function addItem(Item $item): self
    {
        if (!$this->items->contains($item)) {
            $this->items[] = $item;
            $item->setSection($this);
        }

        return $this;
    }

    public function removeItem(Item $item): self
    {
        if ($this->items->contains($item)) {
            $this->items->removeElement($item);
            // set the owning side to null (unless already changed)
            if ($item->getSection() === $this) {
                $item->setSection(null);
            }
        }

        return $this;
    }
}

src/Form/SectionType.php
<?php

namespace App\Form;

use App\Entity\Section;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SectionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('content')
            ->add('position')
            ->add('is_project')
            ->add('is_skill')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Section::class,
        ]);
    }
}

src/Controller/SectionController.php
<?php

namespace App\Controller;

use App\Entity\Section;
use App\Form\Section1Type;
use App\Repository\SectionRepository;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("admin/section")
 */
class SectionController extends Controller
{
    /**
     * @Route("/", name="section_index", methods="GET")
     */
    public function index(SectionRepository $sectionRepository): Response
    {
        return $this->render('section/index.html.twig', ['sections' => $sectionRepository->findAll()]);
    }

    /**
     * @Route("/new", name="section_new", methods="GET|POST")
     */
    function new (Request $request): Response {
        $section = new Section();
        $form = $this->createForm(Section1Type::class, $section);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($section);
            $em->flush();

            return $this->redirectToRoute('section_index');
        }

        return $this->render('section/new.html.twig', [
            'section' => $section,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="section_show", methods="GET")
     */
    public function show(Section $section): Response
    {
        return $this->render('section/show.html.twig', ['section' => $section]);
    }

    /**
     * @Route("/{id}/edit", name="section_edit", methods="GET|POST")
     */
    public function edit(Request $request, Section $section): Response
    {
        $form = $this->createForm(Section1Type::class, $section);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('section_edit', ['id' => $section->getId()]);
        }

        return $this->render('section/edit.html.twig', [
            'section' => $section,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="section_delete", methods="DELETE")
     */
    public function delete(Request $request, Section $section): Response
    {
        if ($this->isCsrfTokenValid('delete' . $section->getId(), $request->request->get('_token'))) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($section);
            $em->flush();
        }

        return $this->redirectToRoute('section_index');
    }
}

templates/section/_delete_form.html.twig
<form method="post" action="{{ path('section_delete', {'id': section.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ section.id) }}">
    <button class="bouton">Supprimer</button>
</form>

templates/section/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="bouton">{{ button_label|default('Sauvegarder') }}</button>
{{ form_end(form) }}

templates/section/edit.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Edit Section{% endblock %}

{% block content %}
    <section class="wrap-bo-section container">
        <div class="row">
            <div class="col-12">
                <div class="back">
                    <a href="{{ path('admin_index') }}">
                        &lt; Back</a>
                </div>
            </div>
        </div>
        <h1>ÉDiter une section - Portfolio</h1>
        <div class="row">
            <div class="col-12">

                {{ include('section/_form.html.twig', {'button_label': 'Mettre à jour'}) }}

                <a href="{{ path('section_index') }}">Retour à la liste</a>

                {{ include('section/_delete_form.html.twig') }}
            </div>
        </div>
    </section>
{% endblock %}

templates/section/index.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Section Backoffice{% endblock %}

{% block content %}

    <section class="wrap-bo-section container">
        <div class="row">
            <div class="col-12">
                <div class="back">
                    <a href="{{ path('admin_index') }}">
                        &lt; Back</a>
                </div>
            </div>
        </div>
        <h1>Section - Portfolio</h1>
        <div class="row">
            <div class="col-12">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Titre</th>
                            <th>Contenu</th>
                            <th>Position (numéro de section)</th>
                            <th>Est-ce un projet ?</th>
                            {# <th>Is_skill</th> #}
                            <th>actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for section in sections %}
                            <tr>
                                <td>{{ section.id }}</td>
                                <td>{{ section.title }}</td>
                                <td>{{ section.content }}</td>
                                <td class="center">{{ section.position }}</td>
                                <td class="center">{{ section.isProject ? 'Yes' : 'No' }}</td>
                                <td class="center">{{ section.isSkill ? 'Yes' : 'No' }}</td>
                                <td>
                                    <a href="{{ path('section_show', {'id': section.id}) }}">Voir</a>
                                    <a href="{{ path('section_edit', {'id': section.id}) }}">Éditer</a>
                                </td>
                            </tr>
                        {% else %}
                            <tr>
                                <td class="msg" colspan="7">aucun enregistrement</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>

                <a href="{{ path('section_new') }}">Nouvelle section</a>
            </div>
        </div>
    </section>
{% endblock %}

templates/section/new.html.twig
{% extends 'layout.html.twig' %}

{% block title %}New Section{% endblock %}

{% block content %}
    <section class="wrap-bo-section container">
        <div class="row">
            <div class="col-12">
                <div class="back">
                    <a href="{{ path('admin_index') }}">
                        &lt; Back</a>
                </div>
            </div>
        </div>
        <h1>Nouvelle section - Portfolio</h1>
        <div class="row">
            <div class="col-12">

                {{ include('section/_form.html.twig') }}

                <a href="{{ path('section_index') }}">Retour à la liste</a>
            </div>
        </div>
    </section>
{% endblock %}

templates/section/show.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Section{% endblock %}

{% block content %}
    <section class="wrap-bo-section container">
        <div class="row">
            <div class="col-12">
                <div class="back">
                    <a href="{{ path('admin_index') }}">
                        &lt; Back</a>
                </div>
            </div>
        </div>
        <h1>Voir la section - Portfolio</h1>
        <div class="row">
            <div class="col-12">
                <table class="table show-section">
                    <tbody>
                        <tr>
                            <th>Id</th>
                            <td>{{ section.id }}</td>
                        </tr>
                        <tr>
                            <th>Title</th>
                            <td>{{ section.title }}</td>
                        </tr>
                        <tr>
                            <th>Content</th>
                            <td>{{ section.content }}</td>
                        </tr>
                        <tr>
                            <th>Position</th>
                            <td>{{ section.position }}</td>
                        </tr>
                        <tr>
                            <th>Is_project</th>
                            <td>{{ section.isProject ? 'Yes' : 'No' }}</td>
                        </tr>
                        <tr>
                            <th>Is_skill</th>
                            <td>{{ section.isSkill ? 'Yes' : 'No' }}</td>
                        </tr>
                    </tbody>
                </table>
                <div class="actions">
                    <a href="{{ path('section_index') }}">Retour à la liste<br></a>

                    <a href="{{ path('section_edit', {'id': section.id}) }}">Éditer</a>

                    {{ include('section/_delete_form.html.twig') }}

                </div>
            </div>
        </section>
    {% endblock %}